/**
 * Generated by scripts/gen-style-rules.mjs. Do not edit by hand.
 *
 * Rule ids and messages come from the upstream Vale style packages so the
 * settings screen can expose per-rule toggles.
 */

export interface StyleRule {
  id: string;
  hint: string;
}

export const STYLE_RULES: Readonly<Record<string, readonly StyleRule[]>> =
  {
  "proselint": [
    {
      "id": "Airlinese",
      "hint": "'…' is airlinese."
    },
    {
      "id": "AnimalLabels",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "Annotations",
      "hint": "'…' left in text."
    },
    {
      "id": "Apologizing",
      "hint": "Excessive apologizing: '…'"
    },
    {
      "id": "Archaisms",
      "hint": "'…' is archaic."
    },
    {
      "id": "But",
      "hint": "Do not start a paragraph with a 'but'."
    },
    {
      "id": "Cliches",
      "hint": "'…' is a cliche."
    },
    {
      "id": "CorporateSpeak",
      "hint": "'…' is corporate speak."
    },
    {
      "id": "Currency",
      "hint": "Incorrect use of symbols in '…'."
    },
    {
      "id": "Cursing",
      "hint": "Consider replacing '…'."
    },
    {
      "id": "DateCase",
      "hint": "With lowercase letters, the periods are standard."
    },
    {
      "id": "DateMidnight",
      "hint": "Use 'midnight' or 'noon'."
    },
    {
      "id": "DateRedundancy",
      "hint": "'a.m.' is always morning; 'p.m.' is always night."
    },
    {
      "id": "DateSpacing",
      "hint": "It's standard to put a space before '…'"
    },
    {
      "id": "DenizenLabels",
      "hint": "Did you mean '…'?"
    },
    {
      "id": "Diacritical",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "GenderBias",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "GroupTerms",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "Hedging",
      "hint": "'…' is hedging."
    },
    {
      "id": "Hyperbole",
      "hint": "'…' is hyperbolic."
    },
    {
      "id": "Jargon",
      "hint": "'…' is jargon."
    },
    {
      "id": "LGBTOffensive",
      "hint": "'…' is offensive. Remove it or consider the context."
    },
    {
      "id": "LGBTTerms",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "Malapropisms",
      "hint": "'…' is a malapropism."
    },
    {
      "id": "Needless",
      "hint": "Prefer '…' over '…'"
    },
    {
      "id": "Nonwords",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "Oxymorons",
      "hint": "'…' is an oxymoron."
    },
    {
      "id": "P-Value",
      "hint": "You should use more decimal places, unless '…' is really true."
    },
    {
      "id": "RASSyndrome",
      "hint": "'…' is redundant."
    },
    {
      "id": "Skunked",
      "hint": "'…' is a bit of a skunked term — impossible to use without issue."
    },
    {
      "id": "Spelling",
      "hint": "Inconsistent spelling of '…'."
    },
    {
      "id": "Typography",
      "hint": "Consider using the '…' symbol instead of '…'."
    },
    {
      "id": "Uncomparables",
      "hint": "'…' is not comparable"
    },
    {
      "id": "Very",
      "hint": "Remove '…'."
    }
  ],
  "google": [
    {
      "id": "Acronyms",
      "hint": "Spell out '…', if it's unfamiliar to the audience."
    },
    {
      "id": "AMPM",
      "hint": "Use 'AM' or 'PM' (preceded by a space)."
    },
    {
      "id": "Colons",
      "hint": "'…' should be in lowercase."
    },
    {
      "id": "Contractions",
      "hint": "Use '…' instead of '…'."
    },
    {
      "id": "DateFormat",
      "hint": "Use 'July 31, 2016' format, not '…'."
    },
    {
      "id": "Ellipses",
      "hint": "In general, don't use an ellipsis."
    },
    {
      "id": "EmDash",
      "hint": "Don't put a space before or after a dash."
    },
    {
      "id": "Exclamation",
      "hint": "Don't use exclamation points in text."
    },
    {
      "id": "FirstPerson",
      "hint": "Avoid first-person pronouns such as '…'."
    },
    {
      "id": "Gender",
      "hint": "Don't use '…' as a gender-neutral pronoun."
    },
    {
      "id": "GenderBias",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "HeadingPunctuation",
      "hint": "Don't put a period at the end of a heading."
    },
    {
      "id": "Headings",
      "hint": "'…' should use sentence-style capitalization."
    },
    {
      "id": "Latin",
      "hint": "Use '…' instead of '…'."
    },
    {
      "id": "LyHyphens",
      "hint": "'…' doesn't need a hyphen."
    },
    {
      "id": "OptionalPlurals",
      "hint": "Don't use plurals in parentheses such as in '…'."
    },
    {
      "id": "Ordinal",
      "hint": "Spell out all ordinal numbers ('…') in text."
    },
    {
      "id": "OxfordComma",
      "hint": "Use the Oxford comma in '…'."
    },
    {
      "id": "Parens",
      "hint": "Use parentheses judiciously."
    },
    {
      "id": "Passive",
      "hint": "In general, use active voice instead of passive voice ('…')."
    },
    {
      "id": "Periods",
      "hint": "Don't use periods with acronyms or initialisms such as '…'."
    },
    {
      "id": "Quotes",
      "hint": "Commas and periods go inside quotation marks."
    },
    {
      "id": "Ranges",
      "hint": "Don't add words such as 'from' or 'between' to describe a range of numbers."
    },
    {
      "id": "Semicolons",
      "hint": "Use semicolons judiciously."
    },
    {
      "id": "Slang",
      "hint": "Don't use internet slang abbreviations such as '…'."
    },
    {
      "id": "Spacing",
      "hint": "'…' should have one space."
    },
    {
      "id": "Spelling",
      "hint": "In general, use American spelling instead of '…'."
    },
    {
      "id": "Units",
      "hint": "Put a nonbreaking space between the number and the unit in '…'."
    },
    {
      "id": "We",
      "hint": "Try to avoid using first-person plural like '…'."
    },
    {
      "id": "Will",
      "hint": "Avoid using '…'."
    },
    {
      "id": "WordList",
      "hint": "Use '…' instead of '…'."
    }
  ],
  "microsoft": [
    {
      "id": "Accessibility",
      "hint": "Don't use language (such as '…') that defines people by their disability."
    },
    {
      "id": "Acronyms",
      "hint": "'…' has no definition."
    },
    {
      "id": "Adverbs",
      "hint": "Remove '…' if it's not important to the meaning of the statement."
    },
    {
      "id": "AMPM",
      "hint": "Use 'AM' or 'PM' (preceded by a space)."
    },
    {
      "id": "Auto",
      "hint": "In general, don't hyphenate '…'."
    },
    {
      "id": "Avoid",
      "hint": "Don't use '…'. See the A-Z word list for details."
    },
    {
      "id": "Contractions",
      "hint": "Use '…' instead of '…'."
    },
    {
      "id": "Dashes",
      "hint": "Remove the spaces around '…'."
    },
    {
      "id": "DateFormat",
      "hint": "Use 'July 31, 2016' format, not '…'."
    },
    {
      "id": "DateNumbers",
      "hint": "Don't use ordinal numbers for dates."
    },
    {
      "id": "DateOrder",
      "hint": "Always spell out the name of the month."
    },
    {
      "id": "Ellipses",
      "hint": "In general, don't use an ellipsis."
    },
    {
      "id": "FirstPerson",
      "hint": "Use first person (such as '…') sparingly."
    },
    {
      "id": "Foreign",
      "hint": "Use '…' instead of '…'."
    },
    {
      "id": "Gender",
      "hint": "Don't use '…'."
    },
    {
      "id": "GenderBias",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "GeneralURL",
      "hint": "For a general audience, use 'address' rather than 'URL'."
    },
    {
      "id": "HeadingAcronyms",
      "hint": "Avoid using acronyms in a title or heading."
    },
    {
      "id": "HeadingColons",
      "hint": "Capitalize '…'."
    },
    {
      "id": "HeadingPunctuation",
      "hint": "Don't use end punctuation in headings."
    },
    {
      "id": "Headings",
      "hint": "'…' should use sentence-style capitalization."
    },
    {
      "id": "Hyphens",
      "hint": "'…' doesn't need a hyphen."
    },
    {
      "id": "Negative",
      "hint": "Form a negative number with an en dash, not a hyphen."
    },
    {
      "id": "Ordinal",
      "hint": "Don't add -ly to an ordinal number."
    },
    {
      "id": "OxfordComma",
      "hint": "Use the Oxford comma in '…'."
    },
    {
      "id": "Passive",
      "hint": "'…' looks like passive voice."
    },
    {
      "id": "Percentages",
      "hint": "Use a numeral plus the units."
    },
    {
      "id": "Plurals",
      "hint": "Don't add '…' to a singular noun. Use plural instead."
    },
    {
      "id": "Quotes",
      "hint": "Punctuation should be inside the quotes."
    },
    {
      "id": "RangeTime",
      "hint": "Use 'to' instead of a dash in '…'."
    },
    {
      "id": "Semicolon",
      "hint": "Try to simplify this sentence."
    },
    {
      "id": "SentenceLength",
      "hint": "Try to keep sentences short (< 30 words)."
    },
    {
      "id": "Spacing",
      "hint": "'…' should have one space."
    },
    {
      "id": "Suspended",
      "hint": "Don't use '…' unless space is limited."
    },
    {
      "id": "Terms",
      "hint": "Prefer '…' over '…'."
    },
    {
      "id": "Units",
      "hint": "Don't spell out the number in '…'."
    },
    {
      "id": "URLFormat",
      "hint": "Use 'of' (not 'for') to describe the relationship of the word URL to a resource."
    },
    {
      "id": "Vocab",
      "hint": "Verify your use of '…' with the A-Z word list."
    },
    {
      "id": "We",
      "hint": "Try to avoid using first-person plural like '…'."
    },
    {
      "id": "Wordiness",
      "hint": "Consider using '…' instead of '…'."
    }
  ],
  "redhat": [
    {
      "id": "Abbreviations",
      "hint": "Do not use periods in all-uppercase abbreviations such as '…'."
    },
    {
      "id": "CaseSensitiveTerms",
      "hint": "Use '…' rather than '…'."
    },
    {
      "id": "Conjunctions",
      "hint": "Do not overuse beginning sentences with '…'."
    },
    {
      "id": "ConsciousLanguage",
      "hint": "Use … rather than '…'."
    },
    {
      "id": "Contractions",
      "hint": "Avoid contractions. Use '…' rather than '….'"
    },
    {
      "id": "Definitions",
      "hint": "Define acronyms and abbreviations (such as '…') on first occurrence if they're likely to be unfamiliar."
    },
    {
      "id": "DoNotUseTerms",
      "hint": "…"
    },
    {
      "id": "Ellipses",
      "hint": "Avoid the ellipsis (...) except to indicate omitted words."
    },
    {
      "id": "EmDash",
      "hint": "Do not use em dashes. Use punctuation marks such as commas, parentheses, or colons instead."
    },
    {
      "id": "GitLinks",
      "hint": "Do not include a link to … unless it is explicitly approved."
    },
    {
      "id": "HeadingPunctuation",
      "hint": "Do not use end punctuation in headings."
    },
    {
      "id": "Headings",
      "hint": "Use sentence-style capitalization in '…'."
    },
    {
      "id": "Hyphens",
      "hint": "Use … rather than '…'."
    },
    {
      "id": "MergeConflictMarkers",
      "hint": "Do not commit Git merge conflict markers in source code."
    },
    {
      "id": "NoGerundsInTitles",
      "hint": "Where possible, avoid using gerunds in topic titles. Use the imperative form instead."
    },
    {
      "id": "ObviousTerms",
      "hint": "Consider not documenting … because it is self-explanatory."
    },
    {
      "id": "OxfordComma",
      "hint": "Use the Oxford comma in '…'."
    },
    {
      "id": "PascalCamelCase",
      "hint": "Consider wrapping this Pascal or Camel case term ('…') in backticks."
    },
    {
      "id": "PassiveVoice",
      "hint": "'…' is passive voice. In general, use active voice. Consult the style guide for acceptable use of passive voice."
    },
    {
      "id": "ProductCentricWriting",
      "hint": "Do not use transitive verb constructions like '…' to grant abilities to inanimate objects. Whenever possible, use direct, user-focused sentences where the subject of the sentence performs the action."
    },
    {
      "id": "ReadabilityGrade",
      "hint": "Simplify your language. The calculated Flesch–Kincaid grade level of … is above the recommended reading grade level of 9."
    },
    {
      "id": "ReleaseNotes",
      "hint": "For release notes, consider using '…' rather than '…'."
    },
    {
      "id": "RepeatedWords",
      "hint": "'…' is repeated."
    },
    {
      "id": "SelfReferentialText",
      "hint": "Avoid using self-referential text such as '…'."
    },
    {
      "id": "SentenceLength",
      "hint": "Try to keep sentences to an average of 32 words or fewer."
    },
    {
      "id": "SessionId",
      "hint": "Do not publish URLs that contain session identifiers. Exposed session IDs enable session hijacking and unauthorized account access."
    },
    {
      "id": "SimpleWords",
      "hint": "Use simple language. Consider using '…' rather than '…'."
    },
    {
      "id": "Slash",
      "hint": "Use either 'or' or 'and' in '…'"
    },
    {
      "id": "SmartQuotes",
      "hint": "Do not use smart quotation marks. Use … rather than …."
    },
    {
      "id": "Spacing",
      "hint": "Keep one space between words in '…'."
    },
    {
      "id": "Spelling",
      "hint": "Verify the word '…'. It is not in the American English or Red Hat terminology spelling dictionaries used by Vale."
    },
    {
      "id": "Symbols",
      "hint": "Do not use the '…' symbol."
    },
    {
      "id": "TermsErrors",
      "hint": "Use '…' rather than '…'."
    },
    {
      "id": "TermsSuggestions",
      "hint": "Depending on the context, consider using '…' rather than '…'."
    },
    {
      "id": "TermsWarnings",
      "hint": "Consider using '…' rather than '…' unless updating existing content that uses the term."
    },
    {
      "id": "UserReplacedValues",
      "hint": "Separate words by underscores in user-replaced values."
    },
    {
      "id": "Using",
      "hint": "Use 'by using' instead of 'using' when it follows a noun for clarity and grammatical correctness."
    }
  ],
  "write-good": [
    {
      "id": "Cliches",
      "hint": "Try to avoid using clichés like '…'."
    },
    {
      "id": "E-Prime",
      "hint": "Try to avoid using '…'."
    },
    {
      "id": "Illusions",
      "hint": "'…' is repeated!"
    },
    {
      "id": "Passive",
      "hint": "'…' may be passive voice. Use active voice if you can."
    },
    {
      "id": "So",
      "hint": "Don't start a sentence with '…'."
    },
    {
      "id": "ThereIs",
      "hint": "Don't start a sentence with '…'."
    },
    {
      "id": "TooWordy",
      "hint": "'…' is too wordy."
    },
    {
      "id": "Weasel",
      "hint": "'…' is a weasel word!"
    }
  ],
  "alex": [
    {
      "id": "Ablist",
      "hint": "When referring to a person, consider using '…' instead of '…'."
    },
    {
      "id": "Condescending",
      "hint": "Using '…' may come across as condescending."
    },
    {
      "id": "Gendered",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "LGBTQ",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "OCD",
      "hint": "When referring to a person, consider using '…' instead of '…'."
    },
    {
      "id": "Press",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "ProfanityLikely",
      "hint": "Don't use '…', it's profane."
    },
    {
      "id": "ProfanityMaybe",
      "hint": "Reconsider using '…', it may be profane."
    },
    {
      "id": "ProfanityUnlikely",
      "hint": "Be careful with '…', it's profane in some cases."
    },
    {
      "id": "Race",
      "hint": "Consider using '…' instead of '…'."
    },
    {
      "id": "Suicide",
      "hint": "Consider using '…' instead of '…' (which may be insensitive)."
    }
  ],
  "joblint": [
    {
      "id": "Acronyms",
      "hint": "Use '…' instead of '…'"
    },
    {
      "id": "Benefits",
      "hint": "Avoid using '…'"
    },
    {
      "id": "Bro",
      "hint": "Avoid using '…'"
    },
    {
      "id": "Competitive",
      "hint": "Avoid using '…'"
    },
    {
      "id": "Derogatory",
      "hint": "Avoid using '…'"
    },
    {
      "id": "DevEnv",
      "hint": "Don't specify a development environment unless absolutely necessary."
    },
    {
      "id": "DumbTitles",
      "hint": "Avoid using '…'"
    },
    {
      "id": "Gendered",
      "hint": "Avoid using '…'"
    },
    {
      "id": "Hair",
      "hint": "Avoid using '…'"
    },
    {
      "id": "LegacyTech",
      "hint": "Avoid using '…'"
    },
    {
      "id": "Meritocracy",
      "hint": "Reevaluate the use of '…'"
    },
    {
      "id": "Profanity",
      "hint": "Remove '…'"
    },
    {
      "id": "Reassure",
      "hint": "Avoid using '…'"
    },
    {
      "id": "Sexualised",
      "hint": "Avoid using '…'"
    },
    {
      "id": "Starter",
      "hint": "Avoid using '…'"
    },
    {
      "id": "TechTerms",
      "hint": "Use '…' instead of '…'"
    },
    {
      "id": "Visionary",
      "hint": "Avoid using '…'"
    }
  ],
  "readability": [
    {
      "id": "AutomatedReadability",
      "hint": "Try to keep the Automated Readability Index (…) below 8."
    },
    {
      "id": "ColemanLiau",
      "hint": "Try to keep the Coleman–Liau Index grade (…) below 9."
    },
    {
      "id": "FleschKincaid",
      "hint": "Try to keep the Flesch–Kincaid grade level (…) below 8."
    },
    {
      "id": "FleschReadingEase",
      "hint": "Try to keep the Flesch reading ease score (…) above 70."
    },
    {
      "id": "GunningFog",
      "hint": "Try to keep the Gunning-Fog index (…) below 10."
    },
    {
      "id": "LIX",
      "hint": "Try to keep the LIX score (…) below 35."
    },
    {
      "id": "SMOG",
      "hint": "Try to keep the SMOG grade (…) below 10."
    }
  ],
  "ai-tells": [
    {
      "id": "AbsoluteAssertions",
      "hint": "AI overreach: '…'. Verify this claim or soften it."
    },
    {
      "id": "AffirmativeFormulas",
      "hint": "AI affirmation: '…'. Cut the flourish and state the point plainly."
    },
    {
      "id": "AIAdjectiveNounPairs",
      "hint": "AI adjective-noun pair: '… …'. Use concrete description instead."
    },
    {
      "id": "AICompoundPhrases",
      "hint": "AI fingerprint: '…'. Rewrite with concrete specifics instead of this clichéd phrase."
    },
    {
      "id": "AnnouncementHeadings",
      "hint": "AI announcement heading: '…'. Cut the heading or rename it to the topic."
    },
    {
      "id": "AnthropomorphicJustification",
      "hint": "AI cliché: '…'. Say what you mean directly."
    },
    {
      "id": "CataphoricForecasting",
      "hint": "AI numbered lead-in: '…'. Present the items or the measured figures directly instead of leading with a count."
    },
    {
      "id": "ClosingPleasantries",
      "hint": "AI closing: '…'. Delete it and end with your actual content."
    },
    {
      "id": "ColloquialAssessments",
      "hint": "AI colloquial assessment: '…'. State the assessment directly."
    },
    {
      "id": "ColonUsage",
      "hint": "AI punctuation: '…'. Lowercase the word after the colon unless it is a proper noun."
    },
    {
      "id": "ConclusionMarkers",
      "hint": "AI conclusion: '…'. Delete this and end on your final point."
    },
    {
      "id": "ContrastiveFormulas",
      "hint": "AI contrast: '…'. State the positive claim directly without the 'not X, but Y' formula."
    },
    {
      "id": "ContrastiveNegation",
      "hint": "AI contrast by negation: '…'. State the positive directly without the trailing negation."
    },
    {
      "id": "DefensiveHedges",
      "hint": "AI defensive hedge: '…'. State your point directly without pre-defending it."
    },
    {
      "id": "DespiteChallenges",
      "hint": "AI despite-formula: '…'. Engage with the challenges substantively or remove the hedge."
    },
    {
      "id": "EmDashUsage",
      "hint": "AI punctuation: em-dash detected. Use a comma, period, or parentheses instead."
    },
    {
      "id": "EmphaticCopula",
      "hint": "AI emphasis: '…'. Remove the italics. Emphasizing a copula rarely adds meaning."
    },
    {
      "id": "EmptyPadding",
      "hint": "AI empty modifier: '… …'. Delete the modifier and keep the noun."
    },
    {
      "id": "EmptyPaddingStacked",
      "hint": "AI empty modifier: '… … …'. Delete the modifier and keep the noun."
    },
    {
      "id": "ExplainerHeadings",
      "hint": "AI explainer heading: '…'. Name what you're explaining instead."
    },
    {
      "id": "FalseBalance",
      "hint": "AI evasion: '…'. Take a clear position or remove the hedge."
    },
    {
      "id": "FalseExclusivity",
      "hint": "AI false exclusivity: '…'. State the point directly without claiming insider knowledge."
    },
    {
      "id": "FigurativeLands",
      "hint": "AI overused verb: '…'. Name the literal action: is merged or is routed to. Disable this rule for aviation or nature prose."
    },
    {
      "id": "FigurativeSits",
      "hint": "AI overused verb: '…'. Name the literal relation: is at or rests with. Disable this rule for furniture or geography prose."
    },
    {
      "id": "FillerPhrases",
      "hint": "AI filler: '…'. Delete this phrase. It adds no meaning."
    },
    {
      "id": "FormalRegister",
      "hint": "AI formalism: '…'. Use a plainer everyday word (e.g., 'use', 'help', 'start')."
    },
    {
      "id": "FormalTransitions",
      "hint": "AI transition: '…'. Delete it, or use a simpler connector like 'and', 'but', or 'so'."
    },
    {
      "id": "GrowthMetaphors",
      "hint": "AI growth metaphor: '…'. Say what literally happens, or disable this rule for medical or nature writing."
    },
    {
      "id": "HedgingPhrases",
      "hint": "AI hedge: '…'. Delete this throat-clearing and state your point directly."
    },
    {
      "id": "LabelAndExplain",
      "hint": "AI label-and-explain: '…'. Fold the noun-phrase label into the sentence it introduces."
    },
    {
      "id": "ListIntroductions",
      "hint": "AI list intro: '…'. Skip the announcement and present the content directly."
    },
    {
      "id": "MarketingHeadings",
      "hint": "AI marketing heading: '…'. Strip the puffery and name the topic plainly."
    },
    {
      "id": "Metacommentary",
      "hint": "AI metacommentary: '…'. Delete it or replace it with substantive content."
    },
    {
      "id": "MicDrop",
      "hint": "AI mic-drop: '…'. Integrate the point into the surrounding text or cut it."
    },
    {
      "id": "MicDropHeadings",
      "hint": "AI mic-drop: '…'. Use a descriptive heading instead."
    },
    {
      "id": "NarrativePivots",
      "hint": "AI narrative pivot: '…'. State your point directly."
    },
    {
      "id": "OpeningCliches",
      "hint": "AI opening: '…'. Start with your actual point instead of this generic lead-in."
    },
    {
      "id": "OrganicConsequence",
      "hint": "AI inevitability: '…'. Say the choice was designed that way."
    },
    {
      "id": "OverusedVocabulary",
      "hint": "AI vocabulary: '…'. Replace with a more specific or common word."
    },
    {
      "id": "OverusedVocabularyVerbs",
      "hint": "AI vocabulary (verb form): '…'. Replace with a direct verb."
    },
    {
      "id": "ParallelStaccato",
      "hint": "AI staccato: '…'. Combine these clipped parallel sentences or vary the structure."
    },
    {
      "id": "ParticipialPadding",
      "hint": "AI participial padding: '…'. Delete it or make the point concrete."
    },
    {
      "id": "PromotionalPuffery",
      "hint": "AI puffery: '…'. Use neutral, specific language."
    },
    {
      "id": "RedundantPrecaution",
      "hint": "AI cliché: '…'. Name the specific safeguard or cut the phrase."
    },
    {
      "id": "ResonateOveruse",
      "hint": "AI overused verb: '…'. Name what connects and why, or disable this rule for physics or audio writing."
    },
    {
      "id": "RestatementMarkers",
      "hint": "AI restatement: '…'. Delete it and trust your original phrasing."
    },
    {
      "id": "RhetoricalDevices",
      "hint": "AI rhetoric: '…'. Remove it or rephrase as a plain statement."
    },
    {
      "id": "RhetoricalSelfAnswer",
      "hint": "AI rhetorical self-answer: '…'. State the point directly instead of posing and answering your own question."
    },
    {
      "id": "SelfReference",
      "hint": "AI cross-reference: '…'. Rewrite the passage to work without the cross-reference."
    },
    {
      "id": "SemicolonUsage",
      "hint": "AI punctuation: '…'. Replace the semicolon with a period or two sentences."
    },
    {
      "id": "SequencingMarkers",
      "hint": "AI sequencing: '…'. Use natural transitions or write an actual list."
    },
    {
      "id": "ServesAsDodge",
      "hint": "AI copula dodge: '…'. Use 'is' or 'are' instead of this inflated construction."
    },
    {
      "id": "ShipOveruse",
      "hint": "AI overused word: '…'. Name the specific action or object. Disable this rule for maritime or logistics writing."
    },
    {
      "id": "StackedAnaphora",
      "hint": "AI anaphora: '…'. Vary the sentence openings or combine into a single statement."
    },
    {
      "id": "StrategyBuzzwords",
      "hint": "AI strategy buzzword: '…'. Describe the actual mechanism or advantage plainly."
    },
    {
      "id": "StructureAnnouncements",
      "hint": "AI structure announcement: '…'. Present the content instead of narrating that you're about to."
    },
    {
      "id": "SycophancyMarkers",
      "hint": "AI sycophancy: '…'. Delete this. It sounds robotic and insincere."
    },
    {
      "id": "UnpackExplore",
      "hint": "AI explainer prompt: '…'. Explain it directly instead of announcing it."
    },
    {
      "id": "UrgencyInflation",
      "hint": "AI urgency: '…'. Delete it or show the stakes concretely."
    },
    {
      "id": "VagueAttributions",
      "hint": "AI vague attribution: '…'. Name the specific source or delete the claim."
    },
    {
      "id": "VerbTricolon",
      "hint": "AI tricolon: '…'. Exactly three parallel verbs in series. Restructure or vary the count."
    },
    {
      "id": "VerbTricolonDensity",
      "hint": "AI tricolon: multiple verb tricolons in one paragraph (found …). Rewrite some with two or four items."
    },
    {
      "id": "WrapUpHeadings",
      "hint": "AI wrap-up heading: '…'. Delete the section or rename the heading to the topic."
    }
  ],
  "openly": [
    {
      "id": "A11Y",
      "hint": "Consider using '…' instead of '…'"
    },
    {
      "id": "Anthropomorphism",
      "hint": "Don't attribute human qualities to software or hardware."
    },
    {
      "id": "But",
      "hint": "Do not start a paragraph with a 'but'."
    },
    {
      "id": "Clarity",
      "hint": "Consider using '…' instead of '…'"
    },
    {
      "id": "E-Prime",
      "hint": "Avoid using \"…\""
    },
    {
      "id": "FutureTense",
      "hint": "Possible future tense."
    },
    {
      "id": "GenderBias",
      "hint": "Consider using '…' instead of '…'"
    },
    {
      "id": "HeadingsPunctuation",
      "hint": "Do not use '…' at the end of headings"
    },
    {
      "id": "Hedging",
      "hint": "Consider removing '…'"
    },
    {
      "id": "Hyphens",
      "hint": "Use '…' instead of '…'"
    },
    {
      "id": "Link",
      "hint": "Don't use 'here' as the content of a link."
    },
    {
      "id": "Punctuation",
      "hint": "Use '…' instead of '…'"
    },
    {
      "id": "QuoteType",
      "hint": "Inconsistent use of '…' ('smart' mixed with 'dumb')"
    },
    {
      "id": "Readability",
      "hint": "Try to keep the Flesch reading ease score (…) above 70."
    },
    {
      "id": "SentenceLength",
      "hint": "Write short sentences (less than 25 words)."
    },
    {
      "id": "So",
      "hint": "Don't start a sentence with '…'"
    },
    {
      "id": "Spelling",
      "hint": "Did you really mean '…'?"
    },
    {
      "id": "ThereIs",
      "hint": "Don't start a sentence with '…'"
    },
    {
      "id": "Titles",
      "hint": "'…' should be in sentence case"
    },
    {
      "id": "UnclearAntecedent",
      "hint": "'…' is an unclear antecedent"
    },
    {
      "id": "VerbingNouns",
      "hint": "Simplify '…' by removing the first word and making the last word a verb."
    }
  ]
};
