#!/usr/bin/env node
/**
 * Vendors the web fonts into public/fonts so nothing at runtime depends on
 * fonts.googleapis.com. Icons and text render even when Google Fonts is
 * slow, blocked, or offline.
 *
 * Downloads each font's css2 stylesheet, mirrors every woff2 locally, and
 * writes public/fonts/fonts.css with the URLs rewritten. index.html loads
 * that single stylesheet.
 *
 * Usage: node scripts/vendor-fonts.mjs
 */
import { execFileSync, execSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// Google serves legacy TTF CSS unless the UA looks like a modern browser.
const UA =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';

/**
 * Icons referenced in the app, from `<mat-icon>name</mat-icon>` in templates
 * and `icon: 'name'` in component code. The symbols font is subset to just
 * these, so re-run this script whenever you add an icon.
 */
function usedIcons() {
  const src = execSync(
    String.raw`grep -rhoE "<mat-icon[^>]*>[a-z0-9_]+</mat-icon>|icon: '[a-z0-9_]+'" src`,
    { encoding: 'utf8' },
  );
  const names = new Set(src.match(/[a-z0-9_]+(?=<|')/g));
  // Icons picked at runtime (ternaries in templates) that the grep can't see.
  for (const name of ['expand_less', 'expand_more', 'history']) names.add(name);
  return [...names].sort();
}

const icons = usedIcons();
if (!icons.length) throw new Error('No mat-icon names found in src');
console.log(`Icons: ${icons.join(', ')}`);

const SHEETS = [
  {
    name: 'google-sans-flex',
    url: 'https://fonts.googleapis.com/css2?family=Google+Sans+Flex:opsz,wght@6..144,1..1000&display=swap',
  },
  {
    name: 'material-symbols-outlined',
    url:
      'https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200' +
      `&icon_names=${icons.join(',')}&display=block`,
  },
];

const outDir = new URL('../public/fonts', import.meta.url).pathname;
mkdirSync(outDir, { recursive: true });
// Clear stale output: filenames are content-hashed, so regenerating with a
// changed icon set would otherwise leave orphaned woff2 files behind.
for (const name of readdirSync(outDir)) rmSync(join(outDir, name));

let css = '/* Generated by scripts/vendor-fonts.mjs — do not edit by hand. */\n';

for (const sheet of SHEETS) {
  let body = execFileSync('curl', ['-fsSL', '-A', UA, sheet.url], { encoding: 'utf8' });
  let index = 0;
  body = body.replace(/https:\/\/fonts\.gstatic\.com\/[^)]+/g, (url) => {
    const tmp = join(outDir, `download-${index}.tmp`);
    execFileSync('curl', ['-fsSL', '-o', tmp, url]);
    // Content-hashed name so browsers can cache the font forever while
    // fonts.css (stable name, no-cache) always points at the current subset.
    const hash = createHash('sha256').update(readFileSync(tmp)).digest('hex').slice(0, 8);
    const file = `${sheet.name}-${String(index++).padStart(2, '0')}.${hash}.woff2`;
    rmSync(join(outDir, file), { force: true });
    execFileSync('mv', [tmp, join(outDir, file)]);
    return file;
  });
  css += `\n/* ${sheet.url} */\n${body}`;
  console.log(`${sheet.name}: ${index} files`);
}

writeFileSync(join(outDir, 'fonts.css'), css);
console.log('Wrote public/fonts/fonts.css');
